<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BSX.Modules.Identity.Domain</RootNamespace>
    <AssemblyName>BSX.Modules.Identity.Domain</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BSX.SharedKernel\BSX.SharedKernel.csproj" />
  </ItemGroup>

</Project>
