<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>BSX.Web</RootNamespace>
    <AssemblyName>BSX.Web</AssemblyName>
    <!-- Required by the Blazor Web App template for enhanced navigation. -->
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BSX.BuildingBlocks\BSX.BuildingBlocks.csproj" />
    <ProjectReference Include="..\BSX.SharedKernel\BSX.SharedKernel.csproj" />
  </ItemGroup>

</Project>
